// import Header from "@/components/Header";
// import PageContainer from "@/components/PageContainer";
// import { readBuses } from "@/lib/services/bus";
// import { Location, readLocations } from "@/lib/services/location";

// import LocationTable from "../LocationTable";

// export default async function Page({ params }: { params: { busId: string } }) {
//   // const locations = await readLocations(params.busId);
//   const buses = await readBuses();
//   const busOptions = buses.map((bus) => ({
//     value: bus.id,
//     label: bus.name,
//     object: bus,
//   }));
//   const locations: Location[] = [
//     {
//       id: "loc-001-am",
//       address: "123 Orchard Road, Singapore 238801",
//       time: "06:30",
//       type: "AM",
//       timeReached: "06:28",
//       position: 1,
//       busId: params.busId,
//       students: [
//         {
//           id: "student-001",
//           fullName: "Tan Wei Ming",
//           givenName: "Wei Ming",
//           gender: "M",
//           level: 3,
//           className: "3A",
//           dateOfBirth: "2015-05-15",
//           nric: "T1234567A",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "123",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-001-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-001",
//           parent: {
//             id: "parent-001",
//             email: "tan.parent@email.com",
//             contact1Name: "Tan Ah Beng",
//             contact1No: "+65 91234567",
//             contact1Relationship: "Father",
//             contact2Name: "Tan Li Hua",
//             contact2No: "+65 91234568",
//             contact2Relationship: "Mother",
//             homePostalCode: "238801",
//             homeUnitNo: "12-34",
//             homeAddress: "123 Orchard Road, Singapore 238801",
//             amPostalCode: "238801",
//             amAddress: "123 Orchard Road, Singapore 238801",
//             pmPostalCode: "238801",
//             pmAddress: "123 Orchard Road, Singapore 238801",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-001",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-002",
//           fullName: "Lee Jia Yi",
//           givenName: "Jia Yi",
//           gender: "F",
//           level: 4,
//           className: "4B",
//           dateOfBirth: "2014-08-22",
//           nric: "S2345678B",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "123",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-001-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-002",
//           parent: {
//             id: "parent-002",
//             email: "lee.parent@email.com",
//             contact1Name: "Lee Ming Teck",
//             contact1No: "+65 92345678",
//             contact1Relationship: "Father",
//             contact2Name: "Lee Mei Ling",
//             contact2No: "+65 92345679",
//             contact2Relationship: "Mother",
//             homePostalCode: "238801",
//             homeUnitNo: "12-35",
//             homeAddress: "123 Orchard Road, Singapore 238801",
//             amPostalCode: "238801",
//             amAddress: "123 Orchard Road, Singapore 238801",
//             pmPostalCode: "238801",
//             pmAddress: "123 Orchard Road, Singapore 238801",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-002",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//       ],
//     },
//     {
//       id: "loc-002-am",
//       address: "456 Marina Bay, Singapore 018956",
//       time: "06:45",
//       type: "AM",
//       timeReached: "06:43",
//       position: 2,
//       busId: params.busId,
//       students: [
//         {
//           id: "student-003",
//           fullName: "Chua Zhi Xuan",
//           givenName: "Zhi Xuan",
//           gender: "M",
//           level: 2,
//           className: "2C",
//           dateOfBirth: "2016-03-10",
//           nric: "T3456789C",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "456",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-002-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-003",
//           parent: {
//             id: "parent-003",
//             email: "chua.parent@email.com",
//             contact1Name: "Chua Boon Heng",
//             contact1No: "+65 93456789",
//             contact1Relationship: "Father",
//             contact2Name: "Chua Su Lin",
//             contact2No: "+65 93456790",
//             contact2Relationship: "Mother",
//             homePostalCode: "018956",
//             homeUnitNo: "10-20",
//             homeAddress: "456 Marina Bay, Singapore 018956",
//             amPostalCode: "018956",
//             amAddress: "456 Marina Bay, Singapore 018956",
//             pmPostalCode: "018956",
//             pmAddress: "456 Marina Bay, Singapore 018956",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-003",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-004",
//           fullName: "Ng Kai Wen",
//           givenName: "Kai Wen",
//           gender: "M",
//           level: 5,
//           className: "5A",
//           dateOfBirth: "2013-11-05",
//           nric: "T4567890D",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "456",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-002-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-004",
//           parent: {
//             id: "parent-004",
//             email: "ng.parent@email.com",
//             contact1Name: "Ng Chee Meng",
//             contact1No: "+65 94567890",
//             contact1Relationship: "Father",
//             contact2Name: "Ng Ai Lian",
//             contact2No: "+65 94567891",
//             contact2Relationship: "Mother",
//             homePostalCode: "018956",
//             homeUnitNo: "10-21",
//             homeAddress: "456 Marina Bay, Singapore 018956",
//             amPostalCode: "018956",
//             amAddress: "456 Marina Bay, Singapore 018956",
//             pmPostalCode: "018956",
//             pmAddress: "456 Marina Bay, Singapore 018956",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-004",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-005",
//           fullName: "Lim Hui Min",
//           givenName: "Hui Min",
//           gender: "F",
//           level: 1,
//           className: "1B",
//           dateOfBirth: "2017-07-18",
//           nric: "S5678901E",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "456",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-002-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-005",
//           parent: {
//             id: "parent-005",
//             email: "lim.parent@email.com",
//             contact1Name: "Lim Seng Huat",
//             contact1No: "+65 95678901",
//             contact1Relationship: "Father",
//             contact2Name: "Lim Pei Choo",
//             contact2No: "+65 95678902",
//             contact2Relationship: "Mother",
//             homePostalCode: "018956",
//             homeUnitNo: "10-22",
//             homeAddress: "456 Marina Bay, Singapore 018956",
//             amPostalCode: "018956",
//             amAddress: "456 Marina Bay, Singapore 018956",
//             pmPostalCode: "018956",
//             pmAddress: "456 Marina Bay, Singapore 018956",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-005",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//       ],
//     },
//     {
//       id: "loc-003-am",
//       address: "789 Jurong East Street 21, Singapore 609602",
//       time: "07:00",
//       type: "AM",
//       timeReached: "06:58",
//       position: 3,
//       busId: params.busId,
//       students: [
//         {
//           id: "student-006",
//           fullName: "Wong Jun Hao",
//           givenName: "Jun Hao",
//           gender: "M",
//           level: 6,
//           className: "6A",
//           dateOfBirth: "2012-09-12",
//           nric: "T6789012F",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "789",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-003-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-006",
//           parent: {
//             id: "parent-006",
//             email: "wong.parent@email.com",
//             contact1Name: "Wong Teck Soon",
//             contact1No: "+65 96789012",
//             contact1Relationship: "Father",
//             contact2Name: "Wong Siew Hoon",
//             contact2No: "+65 96789013",
//             contact2Relationship: "Mother",
//             homePostalCode: "609602",
//             homeUnitNo: "15-30",
//             homeAddress: "789 Jurong East Street 21, Singapore 609602",
//             amPostalCode: "609602",
//             amAddress: "789 Jurong East Street 21, Singapore 609602",
//             pmPostalCode: "609602",
//             pmAddress: "789 Jurong East Street 21, Singapore 609602",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-006",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-007",
//           fullName: "Teo Xin Yi",
//           givenName: "Xin Yi",
//           gender: "F",
//           level: 3,
//           className: "3B",
//           dateOfBirth: "2015-12-25",
//           nric: "S7890123G",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "789",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-003-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-007",
//           parent: {
//             id: "parent-007",
//             email: "teo.parent@email.com",
//             contact1Name: "Teo Boon Kiat",
//             contact1No: "+65 97890123",
//             contact1Relationship: "Father",
//             contact2Name: "Teo Li Lian",
//             contact2No: "+65 97890124",
//             contact2Relationship: "Mother",
//             homePostalCode: "609602",
//             homeUnitNo: "15-31",
//             homeAddress: "789 Jurong East Street 21, Singapore 609602",
//             amPostalCode: "609602",
//             amAddress: "789 Jurong East Street 21, Singapore 609602",
//             pmPostalCode: "609602",
//             pmAddress: "789 Jurong East Street 21, Singapore 609602",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-007",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//       ],
//     },
//     {
//       id: "loc-004-am",
//       address: "321 Tampines Avenue 5, Singapore 529653",
//       time: "07:15",
//       type: "AM",
//       timeReached: "07:13",
//       position: 4,
//       busId: params.busId,
//       students: [
//         {
//           id: "student-008",
//           fullName: "Goh Yi Xuan",
//           givenName: "Yi Xuan",
//           gender: "F",
//           level: 4,
//           className: "4C",
//           dateOfBirth: "2014-04-08",
//           nric: "S8901234H",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "321",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-004-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-008",
//           parent: {
//             id: "parent-008",
//             email: "goh.parent@email.com",
//             contact1Name: "Goh Choon Seng",
//             contact1No: "+65 98901234",
//             contact1Relationship: "Father",
//             contact2Name: "Goh Ai Leng",
//             contact2No: "+65 98901235",
//             contact2Relationship: "Mother",
//             homePostalCode: "529653",
//             homeUnitNo: "08-40",
//             homeAddress: "321 Tampines Avenue 5, Singapore 529653",
//             amPostalCode: "529653",
//             amAddress: "321 Tampines Avenue 5, Singapore 529653",
//             pmPostalCode: "529653",
//             pmAddress: "321 Tampines Avenue 5, Singapore 529653",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-008",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-009",
//           fullName: "Ang Wei Jie",
//           givenName: "Wei Jie",
//           gender: "M",
//           level: 2,
//           className: "2A",
//           dateOfBirth: "2016-10-20",
//           nric: "T9012345I",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "321",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-004-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-009",
//           parent: {
//             id: "parent-009",
//             email: "ang.parent@email.com",
//             contact1Name: "Ang Kok Leong",
//             contact1No: "+65 99012345",
//             contact1Relationship: "Father",
//             contact2Name: "Ang Mei Fong",
//             contact2No: "+65 99012346",
//             contact2Relationship: "Mother",
//             homePostalCode: "529653",
//             homeUnitNo: "08-41",
//             homeAddress: "321 Tampines Avenue 5, Singapore 529653",
//             amPostalCode: "529653",
//             amAddress: "321 Tampines Avenue 5, Singapore 529653",
//             pmPostalCode: "529653",
//             pmAddress: "321 Tampines Avenue 5, Singapore 529653",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-009",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-010",
//           fullName: "Yeo Si Min",
//           givenName: "Si Min",
//           gender: "F",
//           level: 5,
//           className: "5B",
//           dateOfBirth: "2013-02-14",
//           nric: "S0123456J",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "321",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-004-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-010",
//           parent: {
//             id: "parent-010",
//             email: "yeo.parent@email.com",
//             contact1Name: "Yeo Seng Chye",
//             contact1No: "+65 90123456",
//             contact1Relationship: "Father",
//             contact2Name: "Yeo Bee Choo",
//             contact2No: "+65 90123457",
//             contact2Relationship: "Mother",
//             homePostalCode: "529653",
//             homeUnitNo: "08-42",
//             homeAddress: "321 Tampines Avenue 5, Singapore 529653",
//             amPostalCode: "529653",
//             amAddress: "321 Tampines Avenue 5, Singapore 529653",
//             pmPostalCode: "529653",
//             pmAddress: "321 Tampines Avenue 5, Singapore 529653",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-010",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//       ],
//     },
//     {
//       id: "loc-005-am",
//       address: "654 Woodlands Drive 62, Singapore 730654",
//       time: "07:30",
//       type: "AM",
//       timeReached: "07:28",
//       position: 5,
//       busId: params.busId,
//       students: [
//         {
//           id: "student-011",
//           fullName: "Ho Kai Le",
//           givenName: "Kai Le",
//           gender: "M",
//           level: 1,
//           className: "1A",
//           dateOfBirth: "2017-06-30",
//           nric: "T1234567K",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "654",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-005-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-011",
//           parent: {
//             id: "parent-011",
//             email: "ho.parent@email.com",
//             contact1Name: "Ho Boon Chye",
//             contact1No: "+65 91234567",
//             contact1Relationship: "Father",
//             contact2Name: "Ho Siew Lian",
//             contact2No: "+65 91234568",
//             contact2Relationship: "Mother",
//             homePostalCode: "730654",
//             homeUnitNo: "12-50",
//             homeAddress: "654 Woodlands Drive 62, Singapore 730654",
//             amPostalCode: "730654",
//             amAddress: "654 Woodlands Drive 62, Singapore 730654",
//             pmPostalCode: "730654",
//             pmAddress: "654 Woodlands Drive 62, Singapore 730654",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-011",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-012",
//           fullName: "Chong Hui En",
//           givenName: "Hui En",
//           gender: "F",
//           level: 6,
//           className: "6B",
//           dateOfBirth: "2012-01-18",
//           nric: "S2345678L",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "654",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-005-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-012",
//           parent: {
//             id: "parent-012",
//             email: "chong.parent@email.com",
//             contact1Name: "Chong Ah Meng",
//             contact1No: "+65 92345678",
//             contact1Relationship: "Father",
//             contact2Name: "Chong Li Hua",
//             contact2No: "+65 92345679",
//             contact2Relationship: "Mother",
//             homePostalCode: "730654",
//             homeUnitNo: "12-51",
//             homeAddress: "654 Woodlands Drive 62, Singapore 730654",
//             amPostalCode: "730654",
//             amAddress: "654 Woodlands Drive 62, Singapore 730654",
//             pmPostalCode: "730654",
//             pmAddress: "654 Woodlands Drive 62, Singapore 730654",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-012",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//       ],
//     },
//     {
//       id: "loc-006-am",
//       address: "987 Pasir Ris Drive 3, Singapore 519498",
//       time: "07:45",
//       type: "AM",
//       timeReached: "07:43",
//       position: 6,
//       busId: params.busId,
//       students: [
//         {
//           id: "student-013",
//           fullName: "Lau Jun Wei",
//           givenName: "Jun Wei",
//           gender: "M",
//           level: 3,
//           className: "3C",
//           dateOfBirth: "2015-09-05",
//           nric: "T3456789M",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "987",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-006-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-013",
//           parent: {
//             id: "parent-013",
//             email: "lau.parent@email.com",
//             contact1Name: "Lau Teck Chuan",
//             contact1No: "+65 93456789",
//             contact1Relationship: "Father",
//             contact2Name: "Lau Ai Lian",
//             contact2No: "+65 93456790",
//             contact2Relationship: "Mother",
//             homePostalCode: "519498",
//             homeUnitNo: "05-60",
//             homeAddress: "987 Pasir Ris Drive 3, Singapore 519498",
//             amPostalCode: "519498",
//             amAddress: "987 Pasir Ris Drive 3, Singapore 519498",
//             pmPostalCode: "519498",
//             pmAddress: "987 Pasir Ris Drive 3, Singapore 519498",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-013",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-014",
//           fullName: "Tay Xin Yu",
//           givenName: "Xin Yu",
//           gender: "F",
//           level: 4,
//           className: "4A",
//           dateOfBirth: "2014-12-10",
//           nric: "S4567890N",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "987",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-006-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-014",
//           parent: {
//             id: "parent-014",
//             email: "tay.parent@email.com",
//             contact1Name: "Tay Boon Kiat",
//             contact1No: "+65 94567890",
//             contact1Relationship: "Father",
//             contact2Name: "Tay Siew Hoon",
//             contact2No: "+65 94567891",
//             contact2Relationship: "Mother",
//             homePostalCode: "519498",
//             homeUnitNo: "05-61",
//             homeAddress: "987 Pasir Ris Drive 3, Singapore 519498",
//             amPostalCode: "519498",
//             amAddress: "987 Pasir Ris Drive 3, Singapore 519498",
//             pmPostalCode: "519498",
//             pmAddress: "987 Pasir Ris Drive 3, Singapore 519498",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-014",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-015",
//           fullName: "Koh Zhi Hao",
//           givenName: "Zhi Hao",
//           gender: "M",
//           level: 5,
//           className: "5C",
//           dateOfBirth: "2013-08-22",
//           nric: "T5678901O",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "987",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-006-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-015",
//           parent: {
//             id: "parent-015",
//             email: "koh.parent@email.com",
//             contact1Name: "Koh Chee Meng",
//             contact1No: "+65 95678901",
//             contact1Relationship: "Father",
//             contact2Name: "Koh Ai Leng",
//             contact2No: "+65 95678902",
//             contact2Relationship: "Mother",
//             homePostalCode: "519498",
//             homeUnitNo: "05-62",
//             homeAddress: "987 Pasir Ris Drive 3, Singapore 519498",
//             amPostalCode: "519498",
//             amAddress: "987 Pasir Ris Drive 3, Singapore 519498",
//             pmPostalCode: "519498",
//             pmAddress: "987 Pasir Ris Drive 3, Singapore 519498",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-015",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//       ],
//     },
//     {
//       id: "loc-007-am",
//       address: "147 Bishan Street 11, Singapore 570147",
//       time: "08:00",
//       type: "AM",
//       timeReached: "07:58",
//       position: 7,
//       busId: params.busId,
//       students: [
//         {
//           id: "student-016",
//           fullName: "Sim Yi Xuan",
//           givenName: "Yi Xuan",
//           gender: "F",
//           level: 2,
//           className: "2B",
//           dateOfBirth: "2016-11-28",
//           nric: "S6789012P",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "147",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-007-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-016",
//           parent: {
//             id: "parent-016",
//             email: "sim.parent@email.com",
//             contact1Name: "Sim Boon Heng",
//             contact1No: "+65 96789012",
//             contact1Relationship: "Father",
//             contact2Name: "Sim Li Lian",
//             contact2No: "+65 96789013",
//             contact2Relationship: "Mother",
//             homePostalCode: "570147",
//             homeUnitNo: "03-70",
//             homeAddress: "147 Bishan Street 11, Singapore 570147",
//             amPostalCode: "570147",
//             amAddress: "147 Bishan Street 11, Singapore 570147",
//             pmPostalCode: "570147",
//             pmAddress: "147 Bishan Street 11, Singapore 570147",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-016",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-017",
//           fullName: "Ong Kai Jie",
//           givenName: "Kai Jie",
//           gender: "M",
//           level: 6,
//           className: "6C",
//           dateOfBirth: "2012-05-15",
//           nric: "T7890123Q",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "147",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-007-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-017",
//           parent: {
//             id: "parent-017",
//             email: "ong.parent@email.com",
//             contact1Name: "Ong Seng Chye",
//             contact1No: "+65 97890123",
//             contact1Relationship: "Father",
//             contact2Name: "Ong Bee Choo",
//             contact2No: "+65 97890124",
//             contact2Relationship: "Mother",
//             homePostalCode: "570147",
//             homeUnitNo: "03-71",
//             homeAddress: "147 Bishan Street 11, Singapore 570147",
//             amPostalCode: "570147",
//             amAddress: "147 Bishan Street 11, Singapore 570147",
//             pmPostalCode: "570147",
//             pmAddress: "147 Bishan Street 11, Singapore 570147",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-017",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//       ],
//     },
//     {
//       id: "loc-008-am",
//       address: "258 Ang Mo Kio Avenue 8, Singapore 560258",
//       time: "08:15",
//       type: "AM",
//       timeReached: "08:13",
//       position: 8,
//       busId: params.busId,
//       students: [
//         {
//           id: "student-018",
//           fullName: "Pang Wei Min",
//           givenName: "Wei Min",
//           gender: "M",
//           level: 1,
//           className: "1C",
//           dateOfBirth: "2017-04-03",
//           nric: "T8901234R",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "258",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-008-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-018",
//           parent: {
//             id: "parent-018",
//             email: "pang.parent@email.com",
//             contact1Name: "Pang Choon Seng",
//             contact1No: "+65 98901234",
//             contact1Relationship: "Father",
//             contact2Name: "Pang Ai Leng",
//             contact2No: "+65 98901235",
//             contact2Relationship: "Mother",
//             homePostalCode: "560258",
//             homeUnitNo: "11-80",
//             homeAddress: "258 Ang Mo Kio Avenue 8, Singapore 560258",
//             amPostalCode: "560258",
//             amAddress: "258 Ang Mo Kio Avenue 8, Singapore 560258",
//             pmPostalCode: "560258",
//             pmAddress: "258 Ang Mo Kio Avenue 8, Singapore 560258",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-018",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-019",
//           fullName: "Quek Hui Yi",
//           givenName: "Hui Yi",
//           gender: "F",
//           level: 4,
//           className: "4D",
//           dateOfBirth: "2014-07-19",
//           nric: "S9012345S",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "258",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-008-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-019",
//           parent: {
//             id: "parent-019",
//             email: "quek.parent@email.com",
//             contact1Name: "Quek Boon Kiat",
//             contact1No: "+65 99012345",
//             contact1Relationship: "Father",
//             contact2Name: "Quek Siew Hoon",
//             contact2No: "+65 99012346",
//             contact2Relationship: "Mother",
//             homePostalCode: "560258",
//             homeUnitNo: "11-81",
//             homeAddress: "258 Ang Mo Kio Avenue 8, Singapore 560258",
//             amPostalCode: "560258",
//             amAddress: "258 Ang Mo Kio Avenue 8, Singapore 560258",
//             pmPostalCode: "560258",
//             pmAddress: "258 Ang Mo Kio Avenue 8, Singapore 560258",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-019",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-020",
//           fullName: "Rahman Ahmad",
//           givenName: "Ahmad",
//           gender: "M",
//           level: 3,
//           className: "3D",
//           dateOfBirth: "2015-10-25",
//           nric: "T0123456T",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "258",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-008-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-020",
//           parent: {
//             id: "parent-020",
//             email: "rahman.parent@email.com",
//             contact1Name: "Rahman Bin Abdullah",
//             contact1No: "+65 90123456",
//             contact1Relationship: "Father",
//             contact2Name: "Rahman Siti",
//             contact2No: "+65 90123457",
//             contact2Relationship: "Mother",
//             homePostalCode: "560258",
//             homeUnitNo: "11-82",
//             homeAddress: "258 Ang Mo Kio Avenue 8, Singapore 560258",
//             amPostalCode: "560258",
//             amAddress: "258 Ang Mo Kio Avenue 8, Singapore 560258",
//             pmPostalCode: "560258",
//             pmAddress: "258 Ang Mo Kio Avenue 8, Singapore 560258",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-020",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//       ],
//     },
//     {
//       id: "loc-009-am",
//       address: "369 Clementi Avenue 5, Singapore 120369",
//       time: "08:30",
//       type: "AM",
//       timeReached: "08:28",
//       position: 9,
//       busId: params.busId,
//       students: [
//         {
//           id: "student-021",
//           fullName: "Soh Jun Xian",
//           givenName: "Jun Xian",
//           gender: "M",
//           level: 5,
//           className: "5D",
//           dateOfBirth: "2013-03-20",
//           nric: "T1234567U",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "369",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-009-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-021",
//           parent: {
//             id: "parent-021",
//             email: "soh.parent@email.com",
//             contact1Name: "Soh Teck Chuan",
//             contact1No: "+65 91234567",
//             contact1Relationship: "Father",
//             contact2Name: "Soh Li Lian",
//             contact2No: "+65 91234568",
//             contact2Relationship: "Mother",
//             homePostalCode: "120369",
//             homeUnitNo: "07-90",
//             homeAddress: "369 Clementi Avenue 5, Singapore 120369",
//             amPostalCode: "120369",
//             amAddress: "369 Clementi Avenue 5, Singapore 120369",
//             pmPostalCode: "120369",
//             pmAddress: "369 Clementi Avenue 5, Singapore 120369",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-021",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-022",
//           fullName: "Toh Yi En",
//           givenName: "Yi En",
//           gender: "F",
//           level: 2,
//           className: "2D",
//           dateOfBirth: "2016-12-08",
//           nric: "S2345678V",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "369",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-009-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-022",
//           parent: {
//             id: "parent-022",
//             email: "toh.parent@email.com",
//             contact1Name: "Toh Boon Heng",
//             contact1No: "+65 92345678",
//             contact1Relationship: "Father",
//             contact2Name: "Toh Ai Lian",
//             contact2No: "+65 92345679",
//             contact2Relationship: "Mother",
//             homePostalCode: "120369",
//             homeUnitNo: "07-91",
//             homeAddress: "369 Clementi Avenue 5, Singapore 120369",
//             amPostalCode: "120369",
//             amAddress: "369 Clementi Avenue 5, Singapore 120369",
//             pmPostalCode: "120369",
//             pmAddress: "369 Clementi Avenue 5, Singapore 120369",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-022",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//       ],
//     },
//     {
//       id: "loc-010-am",
//       address: "741 Toa Payoh Lorong 6, Singapore 310741",
//       time: "08:45",
//       type: "AM",
//       timeReached: "08:43",
//       position: 10,
//       busId: params.busId,
//       students: [
//         {
//           id: "student-023",
//           fullName: "Voon Kai Le",
//           givenName: "Kai Le",
//           gender: "M",
//           level: 6,
//           className: "6D",
//           dateOfBirth: "2012-06-14",
//           nric: "T3456789W",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "741",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-010-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-023",
//           parent: {
//             id: "parent-023",
//             email: "voon.parent@email.com",
//             contact1Name: "Voon Choon Seng",
//             contact1No: "+65 93456789",
//             contact1Relationship: "Father",
//             contact2Name: "Voon Ai Leng",
//             contact2No: "+65 93456790",
//             contact2Relationship: "Mother",
//             homePostalCode: "310741",
//             homeUnitNo: "09-100",
//             homeAddress: "741 Toa Payoh Lorong 6, Singapore 310741",
//             amPostalCode: "310741",
//             amAddress: "741 Toa Payoh Lorong 6, Singapore 310741",
//             pmPostalCode: "310741",
//             pmAddress: "741 Toa Payoh Lorong 6, Singapore 310741",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-023",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-024",
//           fullName: "Wee Xin Yi",
//           givenName: "Xin Yi",
//           gender: "F",
//           level: 4,
//           className: "4E",
//           dateOfBirth: "2014-01-30",
//           nric: "S4567890X",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "741",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-010-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-024",
//           parent: {
//             id: "parent-024",
//             email: "wee.parent@email.com",
//             contact1Name: "Wee Boon Kiat",
//             contact1No: "+65 94567890",
//             contact1Relationship: "Father",
//             contact2Name: "Wee Siew Hoon",
//             contact2No: "+65 94567891",
//             contact2Relationship: "Mother",
//             homePostalCode: "310741",
//             homeUnitNo: "09-101",
//             homeAddress: "741 Toa Payoh Lorong 6, Singapore 310741",
//             amPostalCode: "310741",
//             amAddress: "741 Toa Payoh Lorong 6, Singapore 310741",
//             pmPostalCode: "310741",
//             pmAddress: "741 Toa Payoh Lorong 6, Singapore 310741",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-024",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//         {
//           id: "student-025",
//           fullName: "Yap Zhi Hao",
//           givenName: "Zhi Hao",
//           gender: "M",
//           level: 1,
//           className: "1D",
//           dateOfBirth: "2017-09-11",
//           nric: "T5678901Y",
//           transportStartDate: "2024-01-15",
//           transportRequirement: "AM",
//           block: "741",
//           status: "Active",
//           amIcon: "📍",
//           pmIcon: "",
//           isFavourite: false,
//           remark: "",
//           schoolId: "school-001",
//           school: {
//             id: "school-001",
//             name: "Example Primary School",
//             initial: "EPS",
//             arrivalTime: "07:30",
//             departureTime: "13:30",
//             email: "admin@eps.edu.sg",
//             password: "password123",
//             isFinalYear: false,
//             isFavourite: false,
//             priceListKey: null,
//             priceListSignedUrl: null,
//             rulesKey: null,
//             rulesSignedUrl: null,
//           },
//           amLocationId: "loc-010-am",
//           amLocation: null,
//           pmLocationId: null,
//           pmLocation: null,
//           parentId: "parent-025",
//           parent: {
//             id: "parent-025",
//             email: "yap.parent@email.com",
//             contact1Name: "Yap Seng Chye",
//             contact1No: "+65 95678901",
//             contact1Relationship: "Father",
//             contact2Name: "Yap Bee Choo",
//             contact2No: "+65 95678902",
//             contact2Relationship: "Mother",
//             homePostalCode: "310741",
//             homeUnitNo: "09-102",
//             homeAddress: "741 Toa Payoh Lorong 6, Singapore 310741",
//             amPostalCode: "310741",
//             amAddress: "741 Toa Payoh Lorong 6, Singapore 310741",
//             pmPostalCode: "310741",
//             pmAddress: "741 Toa Payoh Lorong 6, Singapore 310741",
//             underFas: false,
//             fare: 150,
//             enquiryId: "enquiry-025",
//           },
//           amBusId: params.busId,
//           amBus: null,
//           pmBusId: null,
//           pmBus: null,
//         },
//       ],
//     },
//   ];

//   return (
//     <PageContainer>
//       <Header title="Locations" />
//       <LocationTable data={locations} buses={busOptions} />
//     </PageContainer>
//   );
// }

export default async function Page() {
  return <div>WIP</div>;
}
